MoeMusic/Moe

moe/core/query.py
tests/conftest.py
tests/test_query.py

Using * as the query term presents a shortcut for the user to match all items in the library.

feat(query): add wildcard '*' query

---

alembic/env.py
moe/cli.py
moe/core/config.py
moe/plugins/add.py
moe/plugins/info.py
moe/plugins/ls.py
moe/plugins/rm.py
setup.cfg
tests/conftest.py
tests/test_add.py
tests/test_cli.py
tests/test_config.py
tests/test_info.py
tests/test_ls.py
tests/test_rm.py

Allows us to easily access moe's config on a case-by-casis, and removes the need to annoyingly pass it to each plugin via hooks.

refactor(config): make config a global instance

---

.github/workflows/ci.yml

No reason to run full CI suite if the commit is just an auto-generated version/changelog & tag update.

ci(ci): don't run ci for tag commits

---

.github/workflows/ci.yml

Should help prevent getting api limited by codecov.

ci(ci): only run code coverage once

---

moe/core/library/album.py
moe/core/library/extra.py
moe/core/library/track.py
moe/plugins/add.py
moe/plugins/edit.py
moe/plugins/info.py
moe/plugins/move.py
tests/conftest.py
tests/library/test_album.py
tests/library/test_track.py
tests/test_add.py
tests/test_edit.py
tests/test_write.py

Although we want our lists of library items to only contain unique items, it requires each item to be hashable. By definition of mutability, our library item objects are not hashable and thus would be better served being stored in lists.

refactor(library): convert library sets to lists

---

moe/plugins/add/prompt.py

Makes it more clear what changed in the add prompt by only printing the new track title if it is different from the current track title.

feat(add): only print new track title on prompt if it changed

---

docs/developers/api/moe.plugins.rst
moe/plugins/add/hooks.py
moe/plugins/add/prompt.py
moe/plugins/musicbrainz.py

If we ever decide to use something other than questionary, abstracting the dependency will allow us to change the PromptChoice implementation without changing the API.

refactor(add): abstract questionary dependency from API

---

moe/cli.py
moe/plugins/edit.py
moe/plugins/move.py
moe/plugins/write.py
tests/test_move.py
tests/test_write.py

Previously, we naively used `session.dirty` to inspect a session and determine if any items have been altered. This doesn't work since any flush prior to committing the db will also clean the session out. This change involves adding an sqlalchemy event listener hook to listen for db events so we can properly execute code anytime a new or changed item is introduced to the session.

fix: write and move properly operate on all altered items

---

alembic/versions/b5507b03f9e3_remove_extra_filename.py
moe/core/library/album.py
moe/core/library/extra.py
moe/core/library/lib_item.py
moe/core/library/track.py
moe/core/query.py
moe/plugins/add/add.py
moe/plugins/add/match.py
moe/plugins/edit.py
moe/plugins/move.py
setup.cfg
tests/test_add/test_add.py
tests/test_add/test_match.py
tests/test_edit.py
tests/test_move.py

Previously, items were moved prior to them being successfully added to the database. The issue with this is if an error occurs while adding to the database, but you've already moved the item. This would result in a discrepancy between the file path in the database and the actual file path on the filesystem.

fix(move): don't move items until they've been added to the db

---

moe/plugins/move.py
tests/test_move.py

Upon adding an album, it was getting copied to the root library directory, but the album's path in the library was getting saved as the proper album directory, resulting in a disconnect between the database path and the actual library path.

fix(move): album copies to proper directory on add

---

moe/plugins/info.py
tests/conftest.py
tests/test_info.py

If it seems more useful to print certain track information with the album, I may start just adding them on a case-by-case basis or including an optional way to also print the aggregate track information alongside the album.

refactor(info): album info now only prints album attributes

---

moe/cli.py
moe/plugins/edit.py
moe/plugins/info.py
moe/plugins/list.py
moe/plugins/move.py
moe/plugins/remove.py
moe/plugins/write.py

Primarily, this is to allow us to somewhat control the ordering of hook implementations using `trylast` and `tryfirst`. Mostly, I envisioned this being an issue if attempting to change an item's path before another plugin decided to change that item's title, for example. This is why the `move` plugin is set to `trylast`.
Also, this abstracts some unneeded complexity for plugins when dealing directly with sqlalchemy orm events.

refactor: abstract sqlalchemy orm events into new hook specifications

---

docs/plugins/add.rst
moe/core/library/track.py
tests/library/test_track.py

This lets a track's artist serve as the tag requirement for an albumartist.

feat(add): use 'artist' as a backup for 'albumartist' if missing

---

moe/plugins/add/add.py
moe/plugins/add/prompt.py
tests/test_add/test_prompt.py

Before, it was still adding the original album and just aborting the metadata changes to the album.

fix(add): abort will now abort importing an item entirely

---

codecov.yml

We don't care about coverage of test cases. This will vary according to platform, OS, etc.

test(codecov): remove coverage report from the tests themselves

---

moe/plugins/add/add_cli.py
moe/plugins/add/add_core/add.py
moe/plugins/moe_import/import_cli.py
tests/plugins/add/test_add_cli.py
tests/plugins/import/test_import_cli.py

Aborts are normal exit points for the program, and not really errors.

refactor(cli): aborts now exit with code 0

---

moe/library/album.py
moe/library/extra.py
moe/library/lib_item.py
moe/library/track.py
moe/plugins/info.py
tests/conftest.py
tests/library/test_track.py

Being a set brings it more useful options such as set intersection, union, etc. and can still be sorted if needed.
----
:books: Documentation preview :books:: https://mrmoe--153.org.readthedocs.build/en/153/

refactor: item.fields is now a property returning a set

---

moe/query.py
tests/test_query.py

This may occur if you remove all tracks, and then attempt to remove the album after.
----
:books: Documentation preview :books:: https://mrmoe--158.org.readthedocs.build/en/158/

fix: albums were not querying properly if they didn't contain tracks

---

moe/plugins/move/move_core.py

Always sets an item's path to what Moe expects, even if technically two files are the same. This fixes an issue where a track and album may point to different library folders that technically are the same due to hardlinks.
----
:books: Documentation preview :books:: https://mrmoe--164.org.readthedocs.build/en/164/

fix: relative path error if album and file use non-relative hardlinks

---

moe/util/core/match.py

False negatives were occurring due to large title changes. These changes place less emphasis on the title as well as reducing the overall match value required to determine a match.
----
:books: Documentation preview :books:: https://mrmoe--166.org.readthedocs.build/en/166/

feat: adjusted track match values to be more lenient

---

moe/plugins/add/add_cli.py
moe/plugins/moe_import/import_cli.py
moe/plugins/musicbrainz/mb_cli.py
tests/plugins/add/test_add_cli.py

Skipping the import process will skip adding the item to the library altogether.
----
:books: Documentation preview :books:: https://mrmoe--168.org.readthedocs.build/en/168/

feat(add): new import option to skip a single item

---

moe/plugins/sync/sync_core.py
tests/plugins/sync/test_sync_core.py

----
:books: Documentation preview :books:: https://mrmoe--177.org.readthedocs.build/en/177/

fix: sync_item not called with keyword arguments

---

moe/plugins/musicbrainz/mb_core.py
tests/plugins/musicbrainz/test_mb_core.py

----
:books: Documentation preview :books:: https://mrmoe--179.org.readthedocs.build/en/179/

fix: musicbrainz error if release does not have a country specified

---

moe/plugins/write.py
tests/conftest.py
tests/plugins/test_write.py

Previously, fields changes were only being written if a track had changed
----
:books: Documentation preview :books:: https://mrmoe--197.org.readthedocs.build/en/197/

fix: tags now written to tracks if album fields changed

---

alembic/versions/32e9fea590b7_new_field_track_total.py
docs/fields.rst
moe/library/album.py
moe/library/track.py
moe/plugins/musicbrainz/mb_core.py
moe/plugins/write.py
moe/util/core/match.py
tests/conftest.py
tests/library/test_track.py
tests/plugins/musicbrainz/resources/full_release.py
tests/plugins/test_write.py

New album field representing the total number of tracks belonging to an album. If an album is missing tracks, then len(album.tracks) < album.track_total
----
:books: Documentation preview :books:: https://mrmoe--200.org.readthedocs.build/en/200/

feat: new album field - track_total

---

docs/developers/api/core.rst
docs/developers/contributing.rst
moe/library/album.py
moe/library/extra.py
moe/library/lib_item.py
moe/library/track.py
moe/plugins/moe_import/import_cli.py
moe/plugins/moe_import/import_core.py
moe/plugins/musicbrainz/mb_core.py
moe/util/core/match.py
pyproject.toml
tests/library/test_album.py
tests/library/test_track.py
tests/plugins/musicbrainz/resources/full_release.py
tests/util/core/test_match.py

These classes are used to represent albums and tracks containing only metadata i.e. they do not exist in the filesystem or database. This is useful when describing an album or track from an online source e.g. musicbrainz.
----
:books: Documentation preview :books:: https://mrmoe--207.org.readthedocs.build/en/207/

new MetaTrack and MetaAlbum classes

---

pyproject.toml

Used to implement `None` values for lists if not present until merged into the main repository.
----
:books: Documentation preview :books:: https://mrmoe--212.org.readthedocs.build/en/212/

fix: use fork of mediafile

---

moe/plugins/moe_import/import_cli.py

When looking through candidate albums from Musicbrainz I think it would be nice to print the catalog number beside the label to make sure it's a perfect match when you know the catalog number. This would also help in cases when one label has released the same album under multiple catalog numbers (reissues, different countries, etc.).
This PR prints the catalog number after the label for any album matches during the import process.
```
? Which album would you like to import? (Use shortcuts or arrow keys)
» 1) [77.5%] ABBA - Voulez-Vous
12" Vinyl | FR | Disques Vogue | M27506 | 1979
Musicbrainz: 60843f73-f2b7-3dc7-92ee-8931d7085238
2) [77.5%] ABBA - Voulez-Vous
12" Vinyl | ES | Carnaby | TXS3146 | 1979
Musicbrainz: b2503b44-c366-455b-8a51-689d6a7f6e64
3) [77.5%] ABBA - Voulez-Vous
12" Vinyl …
```

Show catalog number after label during import

---

docs/fields.rst
moe/library/track.py
tests/library/test_track.py

This PR adds `sample_rate` and `bit_depth` as `Track` properties following the discussion in #221 (actionable items 2 and 3).
I updated the docs and tests although MP3 bit depth is unavailable so `mediafile` returns 0 as expected.
I'm not sure if there is a convention on using underscores for property names since `track.albumartist` and `track.audio_format` both exist, but underscores seems to be more common and I find them more readable so I used `bit_depth` and `sample_rate`.
----
:books: Documentation preview :books:: https://mrmoe--228.org.readthedocs.build/en/228/

Add `sample_rate` and `bit_depth` as `Track` properties

---

moe/library/track.py
tests/library/test_track.py
tests/plugins/musicbrainz/resources/full_release.py
tests/plugins/musicbrainz/resources/min_release.py
tests/plugins/musicbrainz/test_mb_core.py

A track's album artist was overwriting the artist field on initialization 
----
:books: Documentation preview :books:: https://mrmoe--230.org.readthedocs.build/en/230/

fix: albumartist overwriting track artist

---

docs/fields.rst
docs/plugins/edit.rst
moe/library/album.py
moe/library/extra.py
moe/library/track.py
moe/plugins/duplicate/dup_cli.py
moe/plugins/list.py
moe/plugins/moe_import/import_core.py
moe/plugins/move/move_core.py
moe/plugins/musicbrainz/mb_cli.py
moe/plugins/musicbrainz/mb_core.py
moe/plugins/remove/rm_core.py
moe/plugins/write.py
tests/library/test_track.py
tests/plugins/add/test_add_cli.py
tests/plugins/import/test_import_cli.py
tests/plugins/import/test_import_core.py
tests/plugins/move/test_move_core.py
tests/plugins/musicbrainz/test_mb_cli.py
tests/plugins/musicbrainz/test_mb_core.py
tests/plugins/test_write.py
tests/test_query.py
tests/util/core/test_match.py

`track.album` now refers to the actual album object (renamed from `track.album_obj`) and `track.albumartist` has been removed. Similarly, `extra.album_obj` has been renamed to `extra.album`.
The original idea was that `track.album` was a string that referred to an album's title, while `track.album_obj` was the actual album object itself. `track.album` and `track.albumartist` were "mapped" attributes of an album directly exposed in the track API due to convention. However, these mapped attributes are not first-class attributes as far as sqlalchemy is concerned, and thus have additional issues and considerations compared to normal attributes. Ultimately, I decided these mapped attributes are not worth the headache.
----
:books: Documentation preview :books:: …

refactor!: rename `album_obj` reference to `album` in tracks and extras

---

alembic/versions/ab5db9861d30_rename_custom_fields.py
docs/developers/api/core.rst
moe/library/album.py
moe/library/extra.py
moe/library/lib_item.py
moe/library/track.py
moe/plugins/duplicate/dup_cli.py
moe/plugins/edit/edit_core.py
moe/plugins/list.py
moe/plugins/musicbrainz/mb_cli.py
moe/plugins/musicbrainz/mb_core.py
moe/query.py
tests/conftest.py
tests/library/test_album.py
tests/library/test_extra.py
tests/library/test_lib_item.py
tests/library/test_track.py
tests/plugins/add/test_add_core.py
tests/plugins/duplicate/test_dup_cli.py
tests/plugins/edit/test_edit_core.py
tests/plugins/musicbrainz/test_mb_cli.py
tests/plugins/musicbrainz/test_mb_core.py
tests/plugins/test_list.py
tests/test_query.py

Custom fields must now be accessed via `item.custom["my_custom_field"]` i.e. normal dictionary access.
I changed this from normal attribute access as overriding `__getattr__` and `__setattr__` (required for transparent attribute access) had some finicky conflicts with sqlalchemy. Also, it preventing type hinting the custom attribute dictionary as well as integration with data serializers such as pydantic.
Overall, the more I used them, the more issues I found, and the more it felt like a hack. I believe the new explicit dictionary access for custom attributes will prove to be more bulletproof. It also explicitly delineates normal and custom attributes which can be useful in some cases.
----
:books: Documentation preview :books:: https://mrmoe--243.org.readthedocs.build/en/243/

refactor!: custom fields now require dictionary access

---

moe/move/move_core.py
tests/move/test_move_core.py

This is more flexible as it allows specifying the direct parent for albums, extras and tracks instead of just albums.
----
:books: Documentation preview :books:: https://mrmoe--250.org.readthedocs.build/en/250/

refactor!: replace lib_path arg for fmt_item_path with optional parent

---

moe/moe_import/import_cli.py
moe/moe_import/import_core.py
tests/add/test_add_cli.py
tests/import/test_import_cli.py
tests/import/test_import_core.py

* `source_str` is now split into two fields: `plugin_source` and `source_id`. This is so in the future we can check against the `plugin_source` and apply different handling criteria per plugin e.g. import weight values.
* `sub_header_info` renamed to `disambigs`. The "sub-header" is specific to the cli, so it was renamed to be more generalized.
----
:books: Documentation preview :books:: https://mrmoe--251.org.readthedocs.build/en/251/

refactor!: changed CandidateAlbum fields

---

docs/query.rst
moe/query.py
moe/util/cli/query.py
tests/test_query.py

Numeric queries can be specified by including two dots ``..`` in the beginning, middle, or end of the value. Dots in the beginning let you specifiy a minimum e.g. ``1..``, dots and the end let you specify a maximum e.g. ``..10``, and dots in the middle let you specify a range e.g. ``1..10``.
Thank you yet again to beets for the inspiration on syntax and documentation.
----
:books: Documentation preview :books:: https://mrmoe--256.org.readthedocs.build/en/256/

Numeric range queries

---

moe/library/extra.py
moe/library/track.py

These hooks are no longer used as of v2.0
note: removing the hookspec won't break anything
----
:books: Documentation preview :books:: https://mrmoe--263.org.readthedocs.build/en/263/

docs: remove references to create_custom_fields hooks

---

docs/configuration.rst

----
📚 Documentation preview 📚: https://mrmoe--279.org.readthedocs.build/en/279/

docs: fix env var used to override the config dir

---

moe/edit/edit_cli.py
moe/edit/edit_core.py
tests/edit/test_edit_cli.py
tests/edit/test_edit_core.py

In the CLI, when editing a field that doesn't exist, moe will give an error. The user now has the option to specify to override this behavior and create the missing field with the `-c` or `--create` flag e.g. `moe edit -c "*" my_new_field=fun`.
This also introduces a new flag to the `edit.edit_item` api command.
----
📚 Documentation preview 📚: https://mrmoe--288.org.readthedocs.build/en/288/

feat(edit): editing fields now allows for creation of new custom fields

---

docs/configuration.rst
moe/move/move_core.py
tests/move/test_move_core.py

This PR adds a new hook to the move plugin called `override_album_path_config` which allows plugins to modify the album path configuration dynamically based on the album's properties.
For more context, see discussion #231.
@jtpavlock I took a stab at implementing the `override_album_path_config` hook we discussed and added some tests which pass locally! But I'm not totally sure that I adhered to moe's design/coding philosophy as I'm still familiarizing myself with the code base. Would appreciate any feedback!
----
📚 Documentation preview 📚: https://mrmoe--281.org.readthedocs.build/en/281/

feat(move): Add `override_album_path_config` hook

---

docs/configuration.rst
moe/move/move_core.py
tests/move/test_move_core.py

I've been finding the `override_album_path_config` hook very helpful and found myself needing similar flexibility to organize extras, especially to be able to put some extras in their own subdirectory.
This PR adds a new `override_extra_path_config` hook (very similar to #281) that allows plugins to completely override the extra path configuration for files based on their properties. I also updated documentation to reflect this change and included tests to verify the functionality of the new hook.
----
📚 Documentation preview 📚: https://mrmoe--299.org.readthedocs.build/en/299/

feat(move): introduce `override_extra_path_config` hook

---

moe/library/album.py
moe/library/track.py
tests/library/test_album.py
tests/library/test_track.py

When reading a multi-disc album from the filesystem and creating its corresponding `album` object, the album's path is now correctly set. This adds a new `album_path` argument to `Track.from_file` that allows the album's path to specifically set rather than defaulting to the track's parent directory.
Fixes #300
----
📚 Documentation preview 📚: https://mrmoe--304.org.readthedocs.build/en/304/

fix(album): multi-disc albums not correctly setting the album's path

---

moe/config.py
tests/add/test_add_cli.py
tests/test_config.py

Log a warning if the user enabled a plugin in their config, but it couldn't be loaded. Also refactors a bit of the plugin loading logic.
----
📚 Documentation preview 📚: https://mrmoe--307.org.readthedocs.build/en/307/

Plugin uninstalled warning

---

docs/configuration.rst
moe/moe_import/__init__.py
moe/moe_import/import_cli.py
tests/import/test_import_cli.py

Introduced a new config option `max_candidates` to control the number of candidate albums displayed during the import process. Updated the import prompt to respect this setting and added validation for the configuration. Included docs and tests.
This option will be useful when using multiple multiple metadata plugins as currently `max_candidates` is hard coded to be 5. The docs mention a `search_limit` config option for the MusicBrainz plugin which is introduced by https://github.com/MoeMusic/moe_musicbrainz/pull/12.
----
📚 Documentation preview 📚: https://mrmoe--302.org.readthedocs.build/en/302/

feat(import): add `max_candidates` config option

---

docs/developers/contributing.rst
docs/fields.rst
moe/library/track.py
moe/moe_alembic/versions/16590851e88e_new_field_composer_sort.py
moe/moe_alembic/versions/31e896e9a709_new_field_composer.py
moe/util/core/match.py
moe/write.py
tests/library/test_track.py
tests/test_write.py

This update introduces two new fields, `composer` and `composer_sort`, to tracks. 
It's my attempt at addressing the issue raised by discussion #282 around adding more track and album metadata. If we can add `composer` and `composer_sort` then we should be able to tag classical music better and I'll have a better understanding of how to add more metadata.
I assume I should also include/generate an Alembic migration, something like
```python
def upgrade():
with op.batch_alter_table("track", schema=None) as batch_op:
batch_op.add_column(sa.Column("composer", sa.String(), nullable=True))
batch_op.add_column(sa.Column("composer_sort", sa.String(), nullable=True))
def downgrade():
with op.batch_alter_table("track", schema=None) as batch_op:
batch_op.drop_column("composer_sort") …
```

feat(track): add `composer` and `composer_sort` fields
