MoeMusic/Moe

- moe/cli.py
- moe/core/config.py
- moe/core/library.py
- moe/core/query.py
- moe/plugins/add.py
- moe/plugins/list.py
- moe/plugins/ls.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_add.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_ls.py
- tests/test_query.py
lots of other random stuff I was too lazy to separate
> Add ls command and basic query functionality

- moe/plugins/add.py
- moe/plugins/move.py
- tests/conftest.py
- tests/test_move.py
> Move plugin

- .github/workflows/prep_release.yml
New secure way to set environment variables in github actions.
> ci(prep_release): uses new github action env var method

- docs/conf.py
- docs/getting_started.rst
- docs/global.rst
- docs/index.rst
- docs/plugins/add.rst
- docs/plugins/edit.rst
- docs/plugins/info.rst
- docs/plugins/ls.rst
- docs/plugins/move.rst
- docs/plugins/plugins.rst
- docs/plugins/rm.rst
- docs/query.rst
- docs/source/moe.plugins.rst
- moe/core/config.py
- moe/core/library/album.py
- moe/core/library/track.py
- moe/core/query.py
- moe/plugins/edit.py
- moe/plugins/info.py
- moe/plugins/ls.py
- moe/plugins/rm.py
- poetry.lock
- pyproject.toml
- tests/test_edit.py
- tests/test_info.py
- tests/test_ls.py
- tests/test_rm.py
Adds ability to edit tags of a track or album.
> feat(edit): add edit plugin

- alembic/versions/32f71e3629db_initial_generation.py
- docs/query.rst
- moe/core/library/album.py
- moe/core/library/extra.py
- moe/core/library/music_item.py
- moe/core/library/session.py
- moe/core/library/track.py
- moe/core/query.py
- moe/plugins/add.py
- moe/plugins/move.py
- tests/conftest.py
- tests/library/test_album.py
- tests/library/test_track.py
- tests/test_add.py
- tests/test_edit.py
- tests/test_info.py
- tests/test_ls.py
- tests/test_move.py
- tests/test_query.py
- tests/test_rm.py
An Album path is now the central point for generating a Track and Extra's path.
> refactor: paths are now based around an Album path

- .github/workflows/ci.yml
- .github/workflows/prep_release.yml
- .github/workflows/release.yml
Various commits not intended to be merged until it's decided Moe is ready for release.
Todo:
> Initial release

- docs/conf.py
- docs/installation.rst
- moe/cli.py
- moe/plugins/musicbrainz.py
- pyproject.toml
> build: mrmoe -> moe

- docs/plugins/move.rst
- moe/plugins/move.py
- tests/test_move.py
Used to move items in the library to reflect any changes in your configuration.
> feat(move): add the `move` command

- pyproject.toml
- setup.cfg
Mypy prefers pyproject.toml to setup.cfg if both are present.
https://mypy.readthedocs.io/en/stable/config_file.html#
> ci(mypy): switch mypy config to pyproject.toml

- .github/scripts/get_latest_changelog.py
- .github/scripts/prep_release.py
- .github/workflows/prep_release.yml
- .github/workflows/release.yml
- .github/workflows/tag_release.yml
- CHANGELOG.rst
- pyproject.toml
New release flow, needs testing
> Release flow

- docs/developers/api/hooks.core.rst
- docs/plugins/move.rst
- docs/plugins/musicbrainz.rst
- moe/cli.py
- moe/config.py
- moe/plugins/move/move_core.py
- moe/plugins/musicbrainz/mb_cli.py
- moe/plugins/musicbrainz/mb_core.py
- moe/plugins/remove/rm_cli.py
- moe/plugins/remove/rm_core.py
- tests/plugins/musicbrainz/test_mb_core.py
- tests/plugins/remove/test_rm_cli.py
- tests/plugins/remove/test_rm_core.py
- tests/test_cli.py
- tests/test_config.py
----
:books: Documentation preview :books:: https://mrmoe--137.org.readthedocs.build/en/137/
> Mb collections

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/resources/__init__.py
- tests/plugins/musicbrainz/resources/collection.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--139.org.readthedocs.build/en/139/
> Mb set collection

- moe/plugins/moe_import/import_cli.py
- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--140.org.readthedocs.build/en/140/
> Update mb album

- docs/developers/api/hooks.core.rst
- moe/library/album.py
- moe/library/track.py
- moe/plugins/duplicate/dup_core.py
- moe/plugins/write.py
- tests/conftest.py
- tests/library/test_album.py
- tests/library/test_track.py
- tests/plugins/add/test_add_cli.py
- tests/plugins/duplicate/test_dup_core.py
- tests/plugins/move/test_move_core.py
- tests/plugins/test_write.py
- tests/test_cli.py
- tests/test_query.py
----
:books: Documentation preview :books:: https://mrmoe--148.org.readthedocs.build/en/148/
> Read and write custom tags

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--149.org.readthedocs.build/en/149/
> feat: read and write musicbrainz IDs

- docs/getting_started.rst
- moe/config.py
- tests/test_config.py
----
:books: Documentation preview :books:: https://mrmoe--152.org.readthedocs.build/en/152/
> feat: new global config option to explicitly disable plugins

- moe/config.py
- moe/library/album.py
- moe/library/extra.py
- moe/plugins/moe_import/import_cli.py
----
:books: Documentation preview :books:: https://mrmoe--155.org.readthedocs.build/en/155/
> docs: hookspec example consistency

- moe/library/album.py
- moe/library/extra.py
- moe/library/lib_item.py
- moe/library/track.py
----
:books: Documentation preview :books:: https://mrmoe--156.org.readthedocs.build/en/156/
> fix: custom fields now populate when loaded from the database

- .readthedocs.yml
- docs/plugins/plugins.rst
- docs/plugins/sync.rst
- moe/config.py
- moe/plugins/add/add_cli.py
- moe/plugins/musicbrainz/mb_core.py
- moe/plugins/sync/__init__.py
- moe/plugins/sync/sync_cli.py
- moe/plugins/sync/sync_core.py
- tests/plugins/add/test_add_cli.py
- tests/plugins/musicbrainz/test_mb_core.py
- tests/plugins/sync/test_sync_cli.py
- tests/plugins/sync/test_sync_core.py
----
:books: Documentation preview :books:: https://mrmoe--160.org.readthedocs.build/en/160/
> Sync plugin

- moe/plugins/moe_import/import_cli.py
- moe/plugins/move/move_core.py
- moe/plugins/musicbrainz/mb_cli.py
----
:books: Documentation preview :books:: https://mrmoe--162.org.readthedocs.build/en/162/
> Fix same file move

- moe/library/lib_item.py
- moe/plugins/list.py
----
:books: Documentation preview :books:: https://mrmoe--170.org.readthedocs.build/en/170/
> feat: list cli output is now sorted

- docs/developers/api/cli.rst
- docs/plugins/musicbrainz.rst
- moe/cli.py
- moe/plugins/edit/edit_cli.py
- moe/plugins/info.py
- moe/plugins/list.py
- moe/plugins/move/move_cli.py
- moe/plugins/musicbrainz/mb_cli.py
- moe/plugins/remove/rm_cli.py
- moe/plugins/sync/sync_cli.py
- moe/util/cli/__init__.py
- moe/util/cli/query.py
- tests/plugins/edit/test_edit_cli.py
- tests/plugins/move/test_move_cli.py
- tests/plugins/musicbrainz/test_mb_cli.py
- tests/plugins/remove/test_rm_cli.py
- tests/plugins/sync/test_sync_cli.py
- tests/plugins/test_info.py
- tests/plugins/test_list.py
- tests/util/cli/test_query.py
----
:books: Documentation preview :books:: https://mrmoe--171.org.readthedocs.build/en/171/
> Collection cli

- docs/conf.py
- docs/developers/api/cli.rst
- docs/developers/api/core.rst
- docs/developers/api/hooks.core.rst
- docs/plugins/move.rst
- moe/plugins/move/move_core.py
- tests/plugins/move/test_move_core.py
----
:books: Documentation preview :books:: https://mrmoe--172.org.readthedocs.build/en/172/
> Custom path template functions

- alembic/script.py.mako
- alembic/versions/30668259fcd6_new_field_country.py
- alembic/versions/60608d9d2908_new_field_media.py
- alembic/versions/817440447857_new_field_label.py
- alembic/versions/fe0956c93730_new_field_artists.py
- docs/fields.rst
- moe/library/album.py
- moe/library/extra.py
- moe/library/track.py
- moe/plugins/edit/edit_core.py
- moe/plugins/write.py
- pyproject.toml
- tests/library/test_track.py
- tests/plugins/edit/test_edit_core.py
- tests/plugins/test_write.py
----
:books: Documentation preview :books:: https://mrmoe--173.org.readthedocs.build/en/173/
> Some new fields

- moe/plugins/moe_import/import_cli.py
- tests/plugins/import/test_import_cli.py
----
:books: Documentation preview :books:: https://mrmoe--174.org.readthedocs.build/en/174/
> feat: add media, label, country, and year to import header

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--181.org.readthedocs.build/en/181/
> fix: musicbrainz error if a release has no label

- docs/developers/api/core.rst
- moe/plugins/moe_import/import_cli.py
- moe/plugins/moe_import/import_core.py
- moe/plugins/musicbrainz/mb_cli.py
- moe/plugins/musicbrainz/mb_core.py
- moe/util/cli/prompt.py
- moe/util/core/match.py
- tests/plugins/add/test_add_cli.py
- tests/plugins/import/test_import_cli.py
- tests/plugins/import/test_import_core.py
- tests/plugins/musicbrainz/resources/full_release.py
- tests/plugins/musicbrainz/test_mb_cli.py
- tests/plugins/musicbrainz/test_mb_core.py
- tests/util/core/test_match.py
----
:books: Documentation preview :books:: https://mrmoe--183.org.readthedocs.build/en/183/
> feat: candidate prompt to select an album to import

- docs/plugins/add.rst
- docs/plugins/edit.rst
- docs/plugins/list.rst
- docs/plugins/move.rst
- docs/plugins/musicbrainz.rst
- docs/plugins/remove.rst
- docs/plugins/sync.rst
- moe/plugins/add/add_cli.py
- moe/plugins/moe_import/import_core.py
- tests/plugins/add/test_add_cli.py
- tests/plugins/import/test_import_core.py
----
:books: Documentation preview :books:: https://mrmoe--184.org.readthedocs.build/en/184/
> Add extras

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- .github/workflows/ci.yml
- .github/workflows/network_test.yml
- .readthedocs.yml
- README.rst
- docs/developers/api/api.rst
- docs/developers/contributing.rst
- docs/developers/developers.rst
- docs/developers/writing_plugins.rst
- docs/getting_started.rst
- docs/plugins/plugins.rst
- moe/plugins/moe_import/import_core.py
- pyproject.toml
----
:books: Documentation preview :books:: https://mrmoe--188.org.readthedocs.build/en/188/
> docs!: update docs for stable release

- alembic/versions/eb8c7e20a080_new_field_barcode.py
- docs/developers/contributing.rst
- docs/fields.rst
- moe/library/album.py
- moe/library/track.py
- moe/plugins/musicbrainz/mb_core.py
- moe/plugins/write.py
- moe/util/core/match.py
- tests/library/test_track.py
- tests/plugins/musicbrainz/resources/full_release.py
- tests/plugins/test_write.py
Adds a new 'barcode' field to an album
----
:books: Documentation preview :books:: https://mrmoe--194.org.readthedocs.build/en/194/
> New barcode field

- docs/developers/api/core.rst
- docs/plugins/plugins.rst
- docs/plugins/read.rst
- moe/config.py
- moe/plugins/duplicate/dup_core.py
- moe/plugins/read/__init__.py
- moe/plugins/read/read_cli.py
- moe/plugins/read/read_core.py
- tests/plugins/read/test_read_cli.py
- tests/plugins/read/test_read_core.py
The read plugin will let Moe catchup to any changes to files in the library that were altered outside of Moe
----
:books: Documentation preview :books:: https://mrmoe--195.org.readthedocs.build/en/195/
> New read plugin for updating items in Moe with any file changes

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/test_mb_core.py
Adds new fields to musicbrainz search criteria to improve result accuracy.
----
:books: Documentation preview :books:: https://mrmoe--198.org.readthedocs.build/en/198/
> feat: improve mb search accuracy

- moe/util/cli/prompt.py
- tests/util/cli/test_prompt.py
----
:books: Documentation preview :books:: https://mrmoe--201.org.readthedocs.build/en/201/
> feat: cli prompts now allow arrow keys to navigate choices

- alembic/versions/0ce5960a081e_new_field_catalog_nums.py
- docs/fields.rst
- moe/library/album.py
- moe/library/lib_item.py
- moe/library/track.py
- moe/plugins/musicbrainz/mb_core.py
- moe/plugins/write.py
- moe/query.py
- moe/util/core/match.py
- pyproject.toml
- tests/library/test_album.py
- tests/library/test_track.py
- tests/plugins/musicbrainz/resources/full_release.py
- tests/plugins/musicbrainz/test_mb_core.py
- tests/plugins/test_write.py
- tests/test_query.py
Multi-value field for catalog numbers of an album.
----
:books: Documentation preview :books:: https://mrmoe--203.org.readthedocs.build/en/203/
> feat: new album field - catalog_nums

- alembic/versions/ab11c34c1d0b_new_field_audio_format.py
- docs/fields.rst
- docs/plugins/musicbrainz.rst
- docs/plugins/plugins.rst
- moe/library/track.py
- tests/conftest.py
- tests/library/test_track.py
- tests/plugins/test_write.py
----
:books: Documentation preview :books:: https://mrmoe--204.org.readthedocs.build/en/204/
> New field: audio format

- alembic/versions/4279789f5739_audio_format_non_null.py
- moe/library/track.py
----
:books: Documentation preview :books:: https://mrmoe--210.org.readthedocs.build/en/210/
> Fix audio format nullable

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/resources/__init__.py
- tests/plugins/musicbrainz/resources/full_release.py
- tests/plugins/musicbrainz/resources/min_release.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--220.org.readthedocs.build/en/220/
> fix: musicbrainz error if release does not have a date or format

- docs/fields.rst
- docs/plugins/move.rst
- docs/query.rst
----
:books: Documentation preview :books:: https://mrmoe--222.org.readthedocs.build/en/222/
> docs: add audio_format field to the docs

- .github/workflows/ci.yml
- .github/workflows/network_test.yml
- .github/workflows/prep_release.yml
- pyproject.toml
----
:books: Documentation preview :books:: https://mrmoe--224.org.readthedocs.build/en/224/
> build: support python 3.11

- moe/plugins/move/move_core.py
- tests/plugins/move/test_move_core.py
Allows specifying the library path the formatted path will be relative to.
----
:books: Documentation preview :books:: https://mrmoe--232.org.readthedocs.build/en/232/
> feat: add new `lib_path` argument to `fmt_item_path`

- moe/plugins/musicbrainz/mb_core.py
- tests/plugins/musicbrainz/test_mb_core.py
----
:books: Documentation preview :books:: https://mrmoe--233.org.readthedocs.build/en/233/
> fix: [none] catalog number from musicbrainz now properly set

- moe/library/track.py
- tests/library/test_track.py
----
:books: Documentation preview :books:: https://mrmoe--235.org.readthedocs.build/en/235/
> fix: ensure tracks created from files contain required tags

- .github/workflows/ci.yml
- .github/workflows/network_test.yml
- .github/workflows/prep_release.yml
- .github/workflows/release.yml
----
:books: Documentation preview :books:: https://mrmoe--236.org.readthedocs.build/en/236/
> ci: upgrade github actions

- docs/developers/writing_plugins.rst
----
:books: Documentation preview :books:: https://mrmoe--238.org.readthedocs.build/en/238/
> docs: add example to writing plugins docs

- README.rst
- docs/developers/api/api.rst
- docs/developers/api/core.rst
----
:books: Documentation preview :books:: https://mrmoe--239.org.readthedocs.build/en/239/
> Usage docs

- docs/plugins/plugins.rst
----
:books: Documentation preview :books:: https://mrmoe--240.org.readthedocs.build/en/240/
> docs: add reference to transcode plugin

- .github/scripts/prep_release.py
- .github/workflows/ci.yml
- .github/workflows/release.yml
----
:books: Documentation preview :books:: https://mrmoe--241.org.readthedocs.build/en/241/
> ci: rename master -> main

- docs/cli.rst
- moe/remove/rm_cli.py
- tests/remove/test_rm_cli.py
----
:books: Documentation preview :books:: https://mrmoe--257.org.readthedocs.build/en/257/
> feat: add option to `rm` command to delete files

- moe/query.py
----
:books: Documentation preview :books:: https://mrmoe--261.org.readthedocs.build/en/261/
> refactor(query): changed numeric range query vars to be clearer

- README.rst
- docs/cli.rst
----
:books: Documentation preview :books:: https://mrmoe--260.org.readthedocs.build/en/260/
> Fixup some docs

- .readthedocs.yml
- README.rst
- docs/developers/api/api.rst
Fixes #269 
----
📚 Documentation preview 📚: https://mrmoe--271.org.readthedocs.build/en/271/
> Fix readme example

- moe/library/album.py
- moe/library/track.py
- tests/library/test_album.py
- tests/library/test_track.py
----
📚 Documentation preview 📚: https://mrmoe--273.org.readthedocs.build/en/273/
> fix: metatracks always failing equality

- .github/workflows/ci.yml
----
📚 Documentation preview 📚: https://mrmoe--275.org.readthedocs.build/en/275/
> ci: add codecov_token to ci

- docs/developers/contributing.rst
----
📚 Documentation preview 📚: https://mrmoe--278.org.readthedocs.build/en/278/
> docs: typo and checklist fix

- docs/getting_started.rst
- docs/third_party_plugins.rst
----
📚 Documentation preview 📚: https://mrmoe--286.org.readthedocs.build/en/286/
> docs: change install docs to recommend pipx

- docs/configuration.rst
Per https://www.dynaconf.com/envvars/
----
📚 Documentation preview 📚: https://mrmoe--287.org.readthedocs.build/en/287/
> docs: fix configuration override environment variables

- docs/cli.rst
- moe/duplicate/dup_core.py
- moe/library/album.py
- moe/library/extra.py
- moe/library/lib_item.py
- moe/library/track.py
- pyproject.toml
- tests/library/test_album.py
- tests/library/test_extra.py
- tests/library/test_track.py
----
📚 Documentation preview 📚: https://mrmoe--297.org.readthedocs.build/en/297/
> Editdocs & is_unique

- docs/developers/contributing.rst
----
📚 Documentation preview 📚: https://mrmoe--306.org.readthedocs.build/en/306/
> docs: simplify alembic contributing docs

- docs/developers/contributing.rst
----
📚 Documentation preview 📚: https://mrmoe--309.org.readthedocs.build/en/309/
> Fixup contrib
